version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # OpenAI API klíč
      - NODE_ENV=production  # Produkční režim
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]  # Kontrola dostupnosti backendu
      interval: 30s  # Interval kontrol
      timeout: 10s
      retries: 3
    restart: unless-stopped  # Restart služby při výpadku
    ports:
      - "8000:8000"  # Mapování portu backendu
    networks:
      - app-network  # Připojení k síti aplikace

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production  # Produkční režim
      - NEXT_PUBLIC_API_URL=${COOLIFY_BACKEND_URL}  # URL backendu pro frontend
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]  # Kontrola dostupnosti frontendu
      interval: 30s  # Interval kontrol
      timeout: 10s
      retries: 3
    restart: unless-stopped  # Restart služby při výpadku
    ports:
      - "3000:3000"  # Mapování portu frontendu
    depends_on:
      - backend  # Závislost na backendu
    networks:
      - app-network  # Připojení k síti aplikace

networks:
  app-network:
    driver: bridge  # Síť typu bridge
